[tool.poetry]
name = "swin-transformer"
version = "0.1.0"
description = "A robust, flexible Swin Transformer package for segmentation tasks."
authors = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "swin_transformer", from = "src" },
    { include = "keras_vision_transformer", from = "src" }
]
[tool.poetry.scripts]
swin-transformer = "swin_transformer.main:main"
