name: Publish to TestPyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry and Twine
        run: python -m pip install --upgrade pip poetry twine

      - name: Configure Poetry to use Python 3.10
        run: poetry env use 3.10

      - name: Install dependencies (no dev)
        run: poetry install --no-interaction --no-ansi --without dev

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository testpypi dist/*.tar.gz dist/*.whl

